# Generated by Django 6.0.3 on 2026-03-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextModels',
            new_name='Fields',
        ),
    ]
