# Generated by Django 6.0.3 on 2026-03-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='product_category',
            field=models.CharField(default='other'),
            preserve_default=False,
        ),
    ]
